name: ArenaPVP
version: '${project.version}'
main: newamazingpvp.arenapvp.ArenaPVP
api-version: '1.20'
commands:
  howmanyplayersareonline:
    description: Says how meany players are online.
    usage: /howmanyplayersareonline

  give_InstaBoomTNT:
    description: Gives InstaBoomTNT
    usage: /give_instaboomtnt

  open_god_menu:
    description: Opens the god menu (ADMINS ONLY)
    usage: /opengodmenu

  pit_restart_server:
    description: Restarts server (ADMINS ONLY)
    usage: /pit_restart_server


